<span style="font-size:20px;"> 학번 : 2021136138
<span style="font-size:20px;"> 이름 : 추승연

>


In [13]:
import torch #PyTorch 모듈 가져오기

In [3]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # 기본적으로 torch.Tensor()는 float32로 생성된다
print(t1.device)  # 텐서가 생성된 장치는 'cpu'이다.
print(t1.requires_grad)  # requires_grad 기본값은 False이다 (자동 미분을 사용하지 않음)
print(t1.size())  # 텐서의 크기는 3이다.
print(t1.shape)   # 텐서의 shape도 크기와 동일하게 3이다

# 만약 GPU가 있다면 아래 코드로 디바이스 변경 가능
# t1_cuda = t1.to(torch.device('cuda'))
# 또는 t1.cuda()로도 가능
t1_cpu = t1.cpu()  # 이미 CPU에 있으므로 변화가 없다

print("#" * 50, 1)

# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # torch.tensor()는 입력값에 따라 dtype을 결정하는데, 이 경우 int64이다.
print(t2.device)  # t2는 'cpu'에서 생성되었다.
print(t2.requires_grad)  # requires_grad는 False이다.
print(t2.size())  # 텐서의 크기는 3이다.
print(t2.shape)  # shape도 size와 동일하게 3이다.

# GPU 디바이스 사용 시
# t2_cuda = t2.to(torch.device('cuda'))
# 또는 t2.cuda()로 가능
t2_cpu = t2.cpu()  # CPU에 있으므로 변화가 없다.

print("#" * 50, 2)

a1 = torch.tensor(1)  # 스칼라 값 하나로 텐서를 생성하면 shape는 빈 크기(0차원)가 된다.
print(a1.shape, a1.ndim)  # 차원은 0이다.

a2 = torch.tensor([1])  # 1차원 벡터로 생성되며, 크기는 [1]이다.
print(a2.shape, a2.ndim)  # 차원은 1이다.

a3 = torch.tensor([1, 2, 3, 4, 5])  # 1차원 벡터로 5개의 값을 가진 텐서이다.
print(a3.shape, a3.ndim)  # 차원은 1이며, 크기는 [5]이다.

a4 = torch.tensor([[1], [2], [3], [4], [5]])  # 2차원 텐서로, 5x1 크기를 가진다.
print(a4.shape, a4.ndim)  # 차원은 2이며, 크기는 [5, 1]이다.

a5 = torch.tensor([  # 2차원 텐서로 3x2 크기를 가진다.
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)  # 차원은 2이며, 크기는 [3, 2]이다.

a6 = torch.tensor([  # 3차원 텐서로 3x2x1 크기를 가진다.
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)  # 차원은 3이며, 크기는 [3, 2, 1]이다.

a7 = torch.tensor([  # 4차원 텐서로 3x1x2x1 크기를 가진다.
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)  # 차원은 4이며, 크기는 [3, 1, 2, 1]이다.

a8 = torch.tensor([  # 4차원 텐서로 3x1x2x3 크기를 가진다.
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)  # 차원은 4이며, 크기는 [3, 1, 2, 3]이다.

a9 = torch.tensor([  # 5차원 텐서로 3x1x2x3x1 크기를 가진다.
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)  # 차원은 5이며, 크기는 [3, 1, 2, 3, 1]이다.

a10 = torch.tensor([  # 2차원 텐서로 4x5 크기를 가진다.
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)  # 차원은 2이며, 크기는 [4, 5]이다.

a10 = torch.tensor([  # 3차원 텐서로 4x1x5 크기를 가진다.
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)  # 차원은 3이며, 크기는 [4, 1, 5]이다.

# 올바르게 크기가 일관된 텐서 생성 예제
a11 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24]],
])
print(a11.shape, a11.ndim)  # 차원은 4이며, 크기는 [4, 2, 3]이다.


torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3
torch.Size([4, 2, 3]) 3



<span style="font-size:20px;"> <span style="color:blue;">b_tensor_initialization_copy


In [5]:
import numpy as np

# 리스트를 사용하여 텐서를 생성
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)  # torch.Tensor() float32 타입의 텐서를 생성함

l2 = [1, 2, 3]
t2 = torch.tensor(l2)  # torch.tensor()는 입력값의 dtype을 자동으로 결정 됨

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)  # torch.as_tensor()는 입력값을 텐서로 변환하되, 입력 리스트의 변경 사항을 반영함

l1[0] = 100  # l1의 첫 번째 요소를 100으로 수정

l2[0] = 100  # l2의 첫 번째 요소를 100으로 수정
l3[0] = 100  # l3의 첫 번째 요소를 100으로 수정

print(t1)  # t1은 l1의 변경 전 상태를 가지고 있음
print(t2)  # t2는 l2의 변경 후 상태를 가지고 있음
print(t3)  # t3은 l3의 변경 후 상태를 가지고 있음

print("#" * 100)

# numpy 배열을 사용하여 텐서를 생성함
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)  # numpy 배열을 torch.Tensor()로 변환하면 float32 텐서가 됨

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)  # numpy 배열을 torch.tensor()로 변환하면 int64 텐서가 됨

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)  # numpy 배열을 torch.as_tensor()로 변환하면 원본 배열의 변경 사항을 반영한다

l4[0] = 100  # l4의 첫 번째 요소를 100으로 수정

l5[0] = 100  # l5의 첫 번째 요소를 100으로 수정
l6[0] = 100  # l6의 첫 번째 요소를 100으로 수정

print(t4)  # t4는 l4의 변경 전 상태를 가지고 있음 (float32 텐서)
print(t5)  # t5는 l5의 변경 후 상태를 가지고 있음 (int64 텐서).
print(t6)  # t6은 l6의 변경 후 상태를 가지고 있음 (변경된 값이 반영됨).


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


<span style="font-size:20px;"> <span style="color:blue;">c_tensor_initialization_constant_values


In [14]:
# 모든 요소가 1로 초기화된 1차원 텐서를 생성한다

t1 = torch.ones(size=(5,))  # 또는 torch.ones(5)와 동일
t1_like = torch.ones_like(input=t1)  # t1과 동일한 크기와 데이터 타입을 가진 텐서를 생성, 값은 모두 1
print(t1)  
print(t1_like) 

# 모든 요소가 0으로 초기화된 1차원 텐서를 생성한다
t2 = torch.zeros(size=(6,))  # 또는 torch.zeros(6)와 동일
t2_like = torch.zeros_like(input=t2)  # t2와 동일한 크기와 데이터 타입을 가진 텐서를 생성, 값은 모두 0
print(t2)  
print(t2_like)  

# 비어 있는(초기화되지 않은) 1차원 텐서를 생성한다.
t3 = torch.empty(size=(4,))  # 또는 torch.empty(4)와 동일
t3_like = torch.empty_like(input=t3)  # t3과 동일한 크기와 데이터 타입을 가진 텐서를 생성, 값은 초기화되지 않음
print(t3)  # 값이 초기화되지 않아 임의의 값을 가질 수 있음
print(t3_like)  # 값이 초기화되지 않아 임의의 값을 가질 수 있음

# 대각선 요소가 1로 초기화된 단위 행렬을 생성한다
t4 = torch.eye(n=3)  # 3x3 크기의 단위 행렬을 생성한다
print(t4)  


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., nan, 0., 0.])
tensor([1., 2., 3., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


<span style="font-size:20px; color:blue;"> d_tensor_initialization_random_valuesues

In [ ]:
# low (10) 이상 high (20) 미만의 정수로 구성된 텐서를 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)  

# 0과 1 사이의 균일한 분포에서 랜덤한 값을 가진 텐서를 생성
t2 = torch.rand(size=(1, 3))
print(t2)  

# 정규 분포(평균 0, 표준편차 1)에서 랜덤한 값을 가진 텐서를 생성
t3 = torch.randn(size=(1, 3))
print(t3)  

# 평균이 10, 표준편차가 1인 정규 분포에서 랜덤한 값을 가진 텐서를 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4) 

# start에서 end까지 균일하게 분포된 값을 가지는 텐서를 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

# 0부터 시작하여 지정된 값까지의 정수로 구성된 텐서를 생성
t6 = torch.arange(5)
print(t6) 

print("#" * 30)

# 랜덤 시드를 설정하여 결과의 재현성을 보장
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1) 

random2 = torch.rand(2, 3)
print(random2) 

print()

# 동일한 시드를 사용하여 생성된 텐서들이 같은 값을 가진다
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)  

random4 = torch.rand(2, 3)
print(random4) 


<span style="font-size:20px; color:blue;"> e_tensor_type_conversion

In [16]:
# 기본적으로 float32 타입으로 2x3 텐서를 생성
a = torch.ones((2, 3))
print(a.dtype)  # 텐서의 데이터 타입은 float32이다

# int16 타입으로 2x3 텐서를 생성
b = torch.ones((2, 3), dtype=torch.int16)
print(b)  # 이 텐서는 int16 타입으로, 값은 모두 1이다

# float64 타입의 랜덤 값을 가지는 2x3 텐서를 생성하고, 모든 값을 20.0으로 스케일링한다
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)  # c 텐서는 float64 타입이고, 랜덤 값에 20.0을 곱한 결과

# int16 타입의 텐서를 int32 타입으로 변환한다
d = b.to(torch.int32)
print(d)  # d 텐서는 int32 타입으로 변환된 텐서이다.

# double (float64) 타입으로 초기화된 10x2 텐서를 생성
double_d = torch.ones(10, 2, dtype=torch.double)

# short (int16) 타입으로 초기화된 1x2 텐서를 생성
short_e = torch.tensor([[1, 2]], dtype=torch.short)

# 10x2 텐서를 생성하고 double (float64) 타입으로 변환한다
double_d = torch.zeros(10, 2).double()

# 10x2 텐서를 생성하고 short (int16) 타입으로 변환한다
short_e = torch.ones(10, 2).short()

# 10x2 텐서를 생성하고 double (float64) 타입으로 변환한다
double_d = torch.zeros(10, 2).to(torch.double)

# 10x2 텐서를 생성하고 short (int16) 타입으로 변환한다
short_e = torch.ones(10, 2).to(dtype=torch.short)

# double (float64) 타입과 short (int16) 타입의 텐서의 데이터 타입을 출력
print(double_d.dtype)  # double_d의 데이터 타입은 float64
print(short_e.dtype)  # short_e의 데이터 타입은 int16

# float64 타입의 랜덤 1차원 텐서를 생성
double_f = torch.rand(5, dtype=torch.double)

# float64 타입의 텐서를 int16 타입으로 변환한다
short_g = double_f.to(torch.short)

# double (float64) 타입 텐서와 short타입 텐서의 곱의 데이터 타입을 출력
print((double_f * short_g).dtype)  # 곱셈 결과의 데이터 타입은 float32이다


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 4.4800,  0.6582, 15.9762],
        [11.1923, 14.8928,  6.7238]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


<span style="font-size:20px; color:blue;"> f_tensor_operations

In [103]:
# 2x3 크기의 모든 값이 1인 텐서를 생성
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))

# 두 텐서를 더합니다. 두 방법 모두 동일한 결과를 생성
t3 = torch.add(t1, t2)  # torch.add() 함수 사용
t4 = t1 + t2           # + 연산자 사용
print(t3)  
print(t4)  

print("#" * 30)

# 두 텐서를 뺀다. 두 방법 모두 동일한 결과를 생성
t5 = torch.sub(t1, t2)  # torch.sub() 함수 사용
t6 = t1 - t2           # - 연산자 사용
print(t5)  
print(t6) 

print("#" * 30)

# 두 텐서를 곱한다. 두 방법 모두 동일한 결과를 생성
t7 = torch.mul(t1, t2)  # torch.mul() 함수 사용
t8 = t1 * t2           # * 연산자 사용
print(t7)  
print(t8) 

print("#" * 30)

# 두 텐서를 나눈다. 두 방법 모두 동일한 결과를 생성
t9 = torch.div(t1, t2)  # torch.div() 함수 사용
t10 = t1 / t2          # / 연산자 사용
print(t9)  
print(t10) 


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


<span style="font-size:20px; color:blue;"> g_tensor_operations_mm

In [ ]:
# 두 벡터의 내적을 계산합니다. 두 텐서 모두 1D 텐서
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())  # 출력: tensor(7) torch.Size([]), 결과는 스칼라 값

# 두 행렬의 곱을 계산
t2 = torch.randn(2, 3)  # 2x3 크기의 랜덤 텐서
t3 = torch.randn(3, 2)  # 3x2 크기의 랜덤 텐서
t4 = torch.mm(t2, t3)  # 행렬 곱셈
print(t4, t4.size())  

# 배치 행렬 곱셈을 수행
t5 = torch.randn(10, 3, 4)  # 배치 차원 10, 3x4 크기의 텐서
t6 = torch.randn(10, 4, 5)  # 배치 차원 10, 4x5 크기의 텐서
t7 = torch.bmm(t5, t6)  # 배치 행렬 곱셈
print(t7.size())  


<span style="font-size:20px; color:blue;"> h_tensor_operations_matmul

In [18]:
import torch

# 벡터와 벡터의 내적 (dot product) 계산
t1 = torch.randn(3)  # 크기 3인 랜덤 벡터
t2 = torch.randn(3)  # 크기 3인 랜덤 벡터
print(torch.matmul(t1, t2).size())  #  스칼라 값)

# 행렬과 벡터의 내적 (broadcasted dot) 계산
t3 = torch.randn(3, 4)  # 크기 (3, 4)인 랜덤 행렬
t4 = torch.randn(4)  # 크기 4의 랜덤 벡터
print(torch.matmul(t3, t4).size())  # 각 행에 대해 벡터와의 내적 결과)

# 배치된 행렬과 벡터의 내적 (broadcasted dot) 계산
t5 = torch.randn(10, 3, 4)  # 크기 (10, 3, 4)인 랜덤 행렬 (배치 크기 10)
t6 = torch.randn(4)  # 크기 4의 랜덤 벡터
print(torch.matmul(t5, t6).size())  # 배치 크기 10, 각 행에 대해 벡터와의 내적 결과

# 배치된 행렬과 배치된 행렬의 행렬 곱 (bmm) 계산
t7 = torch.randn(10, 3, 4)  # 크기 (10, 3, 4)인 랜덤 행렬 (배치 크기 10)
t8 = torch.randn(10, 4, 5)  # 크기 (10, 4, 5)인 랜덤 행렬 (배치 크기 10)
print(torch.matmul(t7, t8).size())  # 배치 크기 10, 각 행렬의 곱 결과

# 배치된 행렬과 행렬의 행렬 곱 (bmm) 계산
t9 = torch.randn(10, 3, 4)  # 크기 (10, 3, 4)인 랜덤 행렬 (배치 크기 10)
t10 = torch.randn(4, 5)  # 크기 (4, 5)인 랜덤 행렬
print(torch.matmul(t9, t10).size())  # 배치 크기 10, 각 행렬의 곱 결과


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


<span style="font-size:20px; color:blue;"> i_tensor_broadcasting

In [7]:

# 1D 텐서와 스칼라 값의 곱셈을 수행
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)  # 각 요소에 스칼라 값을 곱한 결과를 출력한다

print("#" * 50, 1)

# 2D 텐서와 1D 텐서의 차를 계산한다. Broadcasting이 적용
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)  # 각 행에서 1D 텐서의 요소를 빼는 결과를 출력한다

print("#" * 50, 2)

# 2D 텐서에 스칼라 값을 더하거나 빼거나 곱하거나 나눈다. 모든 연산에서 broadcasting이 적용
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # 스칼라 값을 더한 결과
print(t5 - 2.0)  # 스칼라 값을 뺀 결과
print(t5 * 2.0)  # 스칼라 값으로 곱한 결과
print(t5 / 2.0)  # 스칼라 값으로 나눈 결과

print("#" * 50, 3)

# Normalize 함수는 255로 나누어 값을 정규화한다
def normalize(x):
  return x / 255

# 3D 텐서에 대해 normalize 함수를 적용
t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())  # 정규화된 텐서의 크기를 출력

print("#" * 50, 4)

# Broadcasting을 사용하여 텐서의 차원을 맞춰 연산을 수행한다
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # Broadcasting을 통해 t8을 t7에 더한 결과
print(t7 + t9)   # Broadcasting을 통해 t9을 t7에 더한 결과
print(t8 + t9)   # Broadcasting을 통해 t9을 t8에 더한 결과
print(t7 + t10)  # Broadcasting을 통해 t10을 t7에 더한 결과

print("#" * 50, 5)

# Broadcasting을 통해 차원이 맞춰진 텐서의 연산을 수행한다
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3x2 텐서가 t11의 첫 번째 차원에 broadcast됨
print(t12.shape)  # t12의 크기 출력

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3x1 텐서가 t13의 두 번째 차원에 broadcast됨
print(t14.shape)  # t14의 크기 출력

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 1x2 텐서가 t15의 첫 번째 차원에 broadcast됨
print(t16.shape)  # t16의 크기 출력

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 3x1x1 텐서가 t17의 두 번째 차원에 broadcast됨
print((t17 + t18).size())  # 연산 결과 텐서의 크기 출력

print("#" * 50, 6)

# Broadcasting을 통해 차원이 맞춰진 텐서의 연산을 수행한다
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  

# 주석 처리된 코드는 크기 불일치로 인해 실행되지 않음
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())


print("#" * 50, 7)

# 텐서 연산 및 제곱 연산을 수행합니다.
t27 = torch.ones(4) * 5
print(t27)  # 각 요소가 5인 1D 텐서를 출력합니다.

t28 = torch.pow(t27, 2)
print(t28)  # 각 요소의 제곱을 출력합니다.

exp = torch.arange(1., 5.)  # 1부터 4까지의 연속된 숫자로 텐서를 생성합니다.
a = torch.arange(1., 5.)  # 1부터 4까지의 연속된 숫자로 텐서를 생성합니다.
t29 = torch.pow(a, exp)  # 각 요소를 exp 텐서의 해당 요소로 제곱한 결과를 출력합니다.
print(t29)  # 각 요소가 exp의 해당 요소로 제곱된 결과입니다.


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

<span style="font-size:20px; color:blue;">j_tensor_indexing_slicing

In [52]:
# 2D 텐서를 정의
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# 슬라이싱 및 인덱싱 예시
print(x[1])  # 두 번째 행을 선택하여 출력
print(x[:, 1])  # 모든 행에서 두 번째 열의 요소를 선택하여 출력
print(x[1, 2])  # 두 번째 행과 세 번째 열의 단일 요소를 선택하여 출력
print(x[:, -1])  # 모든 행에서 마지막 열의 요소를 선택하여 출력

print("#" * 50, 1)

print(x[1:])  # 두 번째 행부터 끝까지 선택하여 출력
print(x[1:, 3:])  # 두 번째 행부터 끝까지, 네 번째 열부터 끝까지 선택하여 출력

print("#" * 50, 2)

# 6x6 크기의 제로 텐서를 정의
y = torch.zeros((6, 6))
y[1:4, 2] = 1  # 두 번째부터 네 번째 행까지의 세 번째 열을 1로 설정
print(y)  # 수정된 텐서를 출력

print(y[1:4, 1:4])  # 두 번째부터 네 번째 행까지, 두 번째부터 네 번째 열까지의 부분 텐서를 출력

print("#" * 50, 3)

# 2D 텐서를 정의
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])  # 첫 번째와 두 번째 행을 선택하여 출력
print(z[1:, 1:3])  # 두 번째 행부터 끝까지, 두 번째부터 세 번째 열까지 선택하여 출력
print(z[:, 1:])  # 모든 행에서 두 번째 열부터 끝까지 선택하여 출력

# 특정 부분을 수정
z[1:, 1:3] = 0  # 두 번째 행부터 끝까지, 두 번째부터 세 번째 열까지를 0으로 설정
print(z)  # 수정된 텐서를 출력


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


<span style="font-size:20px; color:blue;"> k_tensor_reshaping

In [50]:
# 텐서의 크기를 변경하는 예시

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # 2x3 크기의 텐서를 3x2 크기로 변경
t3 = t1.reshape(1, 6)  # 2x3 크기의 텐서를 1x6 크기로 변경
print(t2)
print(t3)

# 텐서를 생성하고 view를 사용하여 모양을 변경
t4 = torch.arange(8).view(2, 4)  # 8개의 값을 2x4 크기로 보기
t5 = torch.arange(6).view(2, 3)  # 6개의 값을 2x3 크기로 보기
print(t4)
print(t5)

print("#" * 50, 1)

# squeeze()와 unsqueeze() 사용 예시
# squeeze(): 크기가 1인 차원을 제거
t6 = torch.tensor([[[1], [2], [3]]])  # (1, 3, 1) 크기의 텐서 생성
t7 = t6.squeeze()  # 크기가 1인 차원을 모두 제거, 결과는 (3,)
t8 = t6.squeeze(0)  # 첫 번째 차원만 제거, 결과 : (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# unsqueeze(): 새로운 차원을 추가
t9 = torch.tensor([1, 2, 3])  # (3,) 크기의 텐서
t10 = t9.unsqueeze(1)  # 두 번째 차원에 새 축 추가, 결과 : (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # 두 번째 차원에 새 축 추가, 결과 : (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# flatten()
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # (2, 3) 크기의 텐서
t14 = t13.flatten()  # 텐서를 1차원으로 평탄화, 결과 : (6,)
print(t14)

# 복잡한 텐서를 평탄화
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])  # (2, 2, 2) 크기의 텐서
t16 = torch.flatten(t15)  # 전체를 평탄화하여 (8,)
t17 = torch.flatten(t15, start_dim=1)  # 첫 번째 차원 제외하고 평탄화, 결과 : (2, 4)
print(t16)
print(t17)

print("#" * 50, 4)

# permute()  텐서의 차원을 재배치
t18 = torch.randn(2, 3, 5)  # (2, 3, 5) 크기의 랜덤 텐서
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size())  # (5, 2, 3)으로 차원 재배치

# permute와 transpose 차이
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # (2, 3) 크기의 텐서
t20 = torch.permute(t19, dims=(0, 1))  # 순서 그대로, 크기 변화 없음
t21 = torch.permute(t19, dims=(1, 0))  # 차원 재배치하여 (3, 2)
print(t20)
print(t21)

# transpose  두 차원의 위치를 변경
t22 = torch.transpose(t19, 0, 1)  # (3, 2)로 차원 교환
print(t22)

# t()를 사용하여 2D 텐서를 전치
t23 = torch.t(t19)  # 2D 텐서의 전치, 결과 : (3, 2)
print(t23)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


<span style="font-size:20px; color:blue;">l_tensor_concat

In [48]:
import torch

# 다양한 차원에서 텐서를 이어붙이는 예시
# 원본 텐서들
t1 = torch.zeros([2, 1, 3])  # (2, 1, 3) 크기의 제로 텐서
t2 = torch.zeros([2, 3, 3])  # (2, 3, 3) 크기의 제로 텐서
t3 = torch.zeros([2, 2, 3])  # (2, 2, 3) 크기의 제로 텐서

# dim=1을 기준으로 텐서 이어붙이기
t4 = torch.cat([t1, t2, t3], dim=1)  # (2, 6, 3) 크기로 이어붙임
print(t4.shape)

print("#" * 50, 1)

# 1차원 텐서의 이어붙이기
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)  # (8,) 크기로 이어붙임
print(t7.shape)  # >>> torch.Size([8])
print(t7)  

print("#" * 50, 2)

# 2차원 텐서의 이어붙이기
# (2, 3) 크기의 텐서
t8 = torch.arange(0, 6).reshape(2, 3)  
t9 = torch.arange(6, 12).reshape(2, 3) 

# 차원 0을 기준으로 이어붙이기
t10 = torch.cat((t8, t9), dim=0)  # (4, 3) 크기로 이어붙임
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)


# 차원 1을 기준으로 이어붙이기
t11 = torch.cat((t8, t9), dim=1)  # (2, 6) 크기로 이어붙임
print(t11.size())  # >>> torch.Size([2, 6])
print(t11)

print("#" * 50, 3)

# 2차원 텐서 3개 이어붙이기
# (2, 3) 크기의 텐서
t12 = torch.arange(0, 6).reshape(2, 3)  
t13 = torch.arange(6, 12).reshape(2, 3) 
t14 = torch.arange(12, 18).reshape(2, 3)  

# 차원 0을 기준으로 이어붙이기
t15 = torch.cat((t12, t13, t14), dim=0)  # (6, 3) 크기로 이어붙임
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)


# 차원 1을 기준으로 이어붙이기
t16 = torch.cat((t12, t13, t14), dim=1)  # (2, 9) 크기로 이어붙임
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)


print("#" * 50, 4)

# 3차원 텐서의 이어붙이기
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # (1, 2, 3) 크기의 텐서
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # (1, 2, 3) 크기의 텐서

# 차원 0을 기준으로 이어붙이기
t19 = torch.cat((t17, t18), dim=0)  # (2, 2, 3) 크기로 이어붙임
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)



# 차원 1을 기준으로 이어붙이기
t20 = torch.cat((t17, t18), dim=1)  # (1, 4, 3) 크기로 이어붙임
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)

# 차원 2을 기준으로 이어붙이기
t21 = torch.cat((t17, t18), dim=2)  # (1, 2, 6) 크기로 이어붙임
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)



torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

<span style="font-size:20px; color:blue;"> m_tensor_stacking

In [42]:

# 두 개의 2차원 텐서를 정의한다
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# 텐서 t1과 t2를 새로운 차원(dim=0)으로 스택한다
t3 = torch.stack([t1, t2], dim=0)
# t1과 t2에 새로운 차원을 추가한 후, 이 차원을 따라 연결한다

t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
# 두 방법 모두 같은 결과를 생성하므로, 둘의 모양과 내용을 비교한다
print(t3.shape, t3.equal(t4))  

# t1과 t2를 차원 1로 스택한다
t5 = torch.stack([t1, t2], dim=1)
# t1과 t2에 차원 1을 추가한 후, 이 차원을 따라 연결한다
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
# 두 방법 모두 같은 결과를 생성하므로, 둘의 모양과 내용을 비교한다
print(t5.shape, t5.equal(t6)) #torch.Size([2, 2, 3]) True

# t1과 t2를 차원 2로 스택합니다.
t7 = torch.stack([t1, t2], dim=2)
# t1과 t2에 차원 2를 추가한 후, 이 차원을 따라 연결한다
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
# 두 방법 모두 같은 결과를 생성하므로, 둘의 모양과 내용을 비교한다
print(t7.shape, t7.equal(t8))  
print("#" * 50, 1)

# 1차원 텐서를 정의합니다.
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# 두 텐서 모두 크기가 [3]

# t9와 t10을 새로운 차원(dim=0)으로 스택한다
t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  
print(t11)  

# t9와 t10에 차원 0을 추가한 후, 이 차원을 따라 연결한다
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))  

# t9와 t10을 차원 1로 스택한다.
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  
print(t13)

# t9와 t10에 차원 1을 추가한 후, 이 차원을 따라 연결한다
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


<span style="font-size:20px; color:blue;"> n_tensor_vstack_hstack

In [46]:
import torch

# 1차원 텐서 t1과 t2를 수직으로 스택한다
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# 출력: tensor([[1, 2, 3],
#               [4, 5, 6]])
# vstack은 주어진 텐서들을 새로운 차원으로 연결한다.

# 2차원 텐서 t4와 t5를 수직으로 스택한다
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
print(t6)
# 출력: tensor([[1],
#               [2],
#               [3],
#               다

# 3차원 텐서 t7과 t8을 수직으로 스택합니다.
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# 출력: (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# 출력: (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)

print("#" * 50, 1)

# 1차원 텐서 t10과 t11을 수평으로 스택한다
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

# hstack은 주어진 텐서들을 수평으로 연결한다

# 2차원 텐서 t13과 t14를 수평으로 스택한다

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

# 각 텐서의 두 번째 차원(열)으로 연결된다

# 3차원 텐서 t16과 t17을 수평으로 스택한다
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)


t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)


t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

# hstack은 텐서들을 수평으로 연결합니다. 여기서는 두 번째 차원으로 연결된다


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])
